apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTA0TkRBd01UazZhRWQ1YTNOQ1NGSndTMWRHYlhsRE1XRXpjMm89In19fQ==
