apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTA0TXpBNU5UZzZkSGhxVTJkVU4xWjJlR1l0ZGpsNlZHOHlVMDQ9In19fQ==
