apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: frontend
          image: registry.gitlab.com/unsalsenturkk/web-based-todo-list-frontend:f8429ce8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
